### PR TITLE
Hotfix/shraga

### PR DESCRIPTION
**Pull request by Shahar-Y**
added shraga, updated tags to masters

### CODE REVIEW

**Review by omerzamir — DISMISSED** [review]
Did you deploy it? Does it work?

**Comment by Shahar-Y** [comment]
@omerzamir No, for some reason download-service's image in the master didn't upload. Im checking it now. 
Might have something to do with the tests in d-s not passing. Why is it in the master then?

**Comment by omerzamir** [comment]
Yes, it's because tests are not passing.
Ask Yonatan, he'll explain you why.

**Comment by Shahar-Y** [comment]
So I deployed it according to all master versions, and it runs. 
But it doesn't upload the files :(

**Comment by omerzamir** [comment]
@Shahar-Y
Deployed online(Azure) or offline ?
If you deployed it online, did you look what the error of the upload service is? Was it storage or of space error?

**Comment by omerzamir** [comment]
I have to mention it, this branch is not a hotfix/shraga, its a general updates to all services 🤷🏻‍♂️

**Comment by Shahar-Y** [comment]
True, but its just updating the tags, so I don't think its that bad. Also, it might not work with older versions of other services.
and about the error- you are welcome to go to the url with my namespace (its up) and see the error. The request for upload times out, but there is another error before you press any buttons that seems to be related to the authentication

**Comment by yonatandt** [comment]
Closed until shraga will work in the k8s.

**Pull request closed without merging**
